-- Файл: V2__insert_initial_movies_data.sql
-- Вставляем 20 фильмов в таблицу movies

INSERT INTO movies (movie_id, title, description)
VALUES (gen_random_uuid(), 'The Shawshank Redemption',
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'),
       (gen_random_uuid(), 'The Godfather',
        'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.'),
       (gen_random_uuid(), 'The Dark Knight',
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.'),
       (gen_random_uuid(), 'Pulp Fiction',
        'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.'),
       (gen_random_uuid(), 'Forrest Gump',
        'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.'),
       (gen_random_uuid(), 'Inception',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.'),
       (gen_random_uuid(), 'The Matrix',
        'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.'),
       (gen_random_uuid(), 'Goodfellas',
        'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.'),
       (gen_random_uuid(), 'The Silence of the Lambs',
        'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.'),
       (gen_random_uuid(), 'Parasite',
        'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.'),
       (gen_random_uuid(), 'Interstellar',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.'),
       (gen_random_uuid(), 'The Avengers',
        'Earth''s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.'),
       (gen_random_uuid(), 'Spirited Away',
        'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.'),
       (gen_random_uuid(), 'Gladiator',
        'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.'),
       (gen_random_uuid(), 'The Departed',
        'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.'),
       (gen_random_uuid(), 'The Prestige',
        'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.'),
       (gen_random_uuid(), 'The Lion King',
        'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.'),
       (gen_random_uuid(), 'Alien',
        'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.'),
       (gen_random_uuid(), 'Django Unchained',
        'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.'),
       (gen_random_uuid(), 'The Social Network',
        'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.');