spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
